<a href="https://colab.research.google.com/github/marianaufcg/Capacitacao/blob/main/atividadematrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Soluções numéricas**

Seja a EDO de segunda ordem:
\begin{equation} \frac{\mathrm{d}^2 y}{\mathrm{d} x^2} + 5\frac{\mathrm{d} y}{\mathrm{d} x} + 6y = 0
\end{equation}

Definida para x em [0, 2] com as condições de fronteira dadas:

\
\begin{equation}
y(0) = 0
\\ y(2) = 0,2
\end{equation}

\
Pode-se resolver o sistema pelo **Método das Diferenças Finitas** ou pelo **Método dos Operadores**. Isso porque, por aproximação numérica:

\begin{equation}
\ y_{i}' = \frac{y_{i+1} - y_{i-1}}{2h}
\end{equation}

\
\begin{equation}
\ y_{i}'' = \frac{y_{i+1} - 2y_{i} + y_{i-1}}{h^{2}}
\end{equation}

\
E, partindo desses resultados, resolver a EDO por um dos métodos.

\
**Método das Diferenças Finitas**

Substituindo as expressões numéricas na equação inicial, obtém-se a relação de recorrência abaixo:

\
\begin{equation}
\frac{y_{i+1} - 2y_{i} + y_{i-1}}{h^{2}} + 5 \cdot \frac{y_{i+1} - 2y_{i} + y_{i-1}}{h^{2}} + 6 \cdot y_{i} = 0
\end{equation}

\
\begin{equation}
\ y_{i+1}\left ( \frac{1}{h^2} + \frac{5}{2h} \right ) +  y_{i}  \left ( \frac{-2}{h^2} + 6 \right )+ y_{i-1}\left ( \frac{1}{h^2} - \frac{5}{2h} \right )= 0
\end{equation}

\
Que, para um intervalo do domínio discretizado em N pontos, oferece o seguinte sistema:

\
\begin{equation}
 \left\{\begin{matrix}
\alpha \cdot y_n  & +\beta \cdot y_{n-1} &+ \gamma \cdot y_{n-2} & = 0\\
\alpha \cdot y_{n-1}  & +\beta \cdot y_{n-2} &+ \gamma \cdot y_{n-3} & = 0 \\
\alpha \cdot y_{n-2}  & +\beta \cdot y_{n-3} &+ \gamma \cdot y_{n-4} & = 0 \\
 & [...]  & \\
\end{matrix}\right.
\end{equation}

\
Para α e β os valoers:

\
\begin{equation}
\alpha = \frac{1}{h^2} + \frac{5}{2h}
\end{equation}

\
\begin{equation}
\beta = \frac{-2}{h^2} + 6
\end{equation}

\
\begin{equation}
\gamma= \frac{1}{h^2} - \frac{5}{2h}
\end{equation}

\
O que nos leva a um sistema de matrizes. A fins ilustrativos, se N = 5:

\
\begin{equation}
\begin{bmatrix}
\beta & \gamma & 0 & 0 & 0 \\
\alpha & \beta & \gamma & 0 & 0 \\
0 & \alpha & \beta & \gamma & 0 \\
0 & 0 & \alpha & \beta & \gamma  \\
0 & 0 & 0 & \alpha & \beta \\
\end{bmatrix}
\cdot
\begin{bmatrix}
y_5 \\
y_4 \\
y_3 \\
y_2 \\
y_1 \\
\end{bmatrix}
=
\begin{bmatrix}
0 \\
0 \\
0 \\
0 \\
0 \\
\end{bmatrix}
\end{equation}

\
Para incluir no problema a condição de fronteira, deve-se lembrar que:

\
\begin{equation}
\ y_f = 0.2
\\ y_0 = 0
\end{equation}

\
\begin{equation}
\ 0.2\alpha + \beta y_5 + \gamma y_4 = 0
\end{equation}

\
\begin{equation}
\beta y_5 + \gamma y_4 = - 0.2 \alpha
\end{equation}

De forma que o sistema se torna:

\
\begin{equation}
\begin{bmatrix}
\beta & \gamma & 0 & 0 & 0 \\
\alpha & \beta & \gamma & 0 & 0 \\
0 & \alpha & \beta & \gamma & 0 \\
0 & 0 & \alpha & \beta & \gamma  \\
0 & 0 & 0 & \alpha & \beta \\
\end{bmatrix}
\cdot
\begin{bmatrix}
y_5 \\
y_4 \\
y_3 \\
y_2 \\
y_1 \\
\end{bmatrix}
=
\begin{bmatrix}
-0.2\alpha \\
0 \\
0 \\
0 \\
0 \\
\end{bmatrix}
\end{equation}

In [32]:
import numpy as np
import matplotlib.pyplot as plt

n = 4              # Numero de pontos
intervalo = 2
h = intervalo / n   # Espaçamento
cf = 0.2            # Condição de fronteira

# Definindo dominio

x = np.linspace(0, 2, n)

# Parâmetros da matriz

alfa = (1/np.power(h,2)) + (5/2*h)
beta = 6 - (2/np.power(h,2))
gamma = (1/np.power(h,2)) - (5/2*h)

# Matriz dos coeficientes ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

matriz_coeficientes = np.zeros((n, n))

for i in range (0, n):

  matriz_coeficientes[i][i] = beta

  if (i > 0):
    matriz_coeficientes[i][i-1] = alfa

  if (i < n-1):
    matriz_coeficientes[i][i+1] = gamma

# Matriz de zeros ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

zeros = np.zeros((n, 1))
zeros[0][0] = -(cf * alfa)

# Calculo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

matriz_coeficientes_inversa = np.linalg.inv(matriz_coeficientes)

y = np.matmul(matriz_coeficientes_inversa, zeros)

print(matriz_coeficientes)
print(0)
print(zeros)
print( )
print(y)


[[-2.    2.75  0.    0.  ]
 [ 5.25 -2.    2.75  0.  ]
 [ 0.    5.25 -2.    2.75]
 [ 0.    0.    5.25 -2.  ]]
0
[[-1.05]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]]

[[-1.02043495]
 [-1.12395269]
 [ 1.13068295]
 [ 2.96804273]]


**Método dos Operadores.**


In [30]:
import numpy as np
import matplotlib.pyplot as plt

n = 5               # Numero de pontos
intervalo = 2
h = intervalo / n   # Espaçamento
cf = 0.2            # Condição de fronteira

# Matrizes Dx^2 e Dx

matriz_Dx2 = np.zeros((n, n))
matriz_Dx = np.zeros((n, n))

for i in range (0, n):

  matriz_Dx2[i][i] = -2

  if (i > 0):
    matriz_Dx2[i][i-1] = 1
    matriz_Dx[i][i-1] = -1

  if (i < n-1):
    matriz_Dx2[i][i+1] = 1
    matriz_Dx[i][i+1] = 1

matriz_Dx2 = matriz_Dx2 / np.power(h, 2)
matriz_Dx = matriz_Dx / (2*h)

# Operador geral

matriz_operador = matriz_Dx + matriz_Dx2 + (6 * np.identity(n))

# Admitindo a condição de fronteira

matriz_linha = np.zeros((n, 1))
matriz_linha[n-1][0] = -7.5 * cf

# Calculo

matriz_inversa = np.linalg.inv(matriz_operador)
y = np.matmul(matriz_inversa, matriz_linha)

print(matriz_operador)
print()
print(matriz_linha)
print()
print(y)


[[-6.5  7.5  0.   0.   0. ]
 [ 5.  -6.5  7.5  0.   0. ]
 [ 0.   5.  -6.5  7.5  0. ]
 [ 0.   0.   5.  -6.5  7.5]
 [ 0.   0.   0.   5.  -6.5]]

[[ 0. ]
 [ 0. ]
 [ 0. ]
 [ 0. ]
 [-1.5]]

[[-2.18817987]
 [-1.89642255]
 [-0.18477963]
 [ 1.10413935]
 [ 1.08010719]]
